package top.sharex.oes.dao;

import top.sharex.oes.entity.Choice;

import java.util.List;

public interface ChoiceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table choice
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table choice
     *
     * @mbggenerated
     */
    int insert(Choice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table choice
     *
     * @mbggenerated
     */
    int insertSelective(Choice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table choice
     *
     * @mbggenerated
     */
    Choice selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table choice
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Choice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table choice
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(Choice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table choice
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Choice record);

    List<Choice> selectChoicesByQuestionId(Integer questionId);
}