package top.sharex.oes.dao;

import top.sharex.oes.entity.ExamQuestionsPool;

import java.util.List;

public interface ExamQuestionsPoolMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_questions_pool
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_questions_pool
     *
     * @mbggenerated
     */
    int insert(ExamQuestionsPool record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_questions_pool
     *
     * @mbggenerated
     */
    int insertSelective(ExamQuestionsPool record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_questions_pool
     *
     * @mbggenerated
     */
    ExamQuestionsPool selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_questions_pool
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ExamQuestionsPool record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_questions_pool
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ExamQuestionsPool record);

    List<ExamQuestionsPool> selectQuestionPoolByTeacherId(Integer teachId);

    ExamQuestionsPool selectQuestionPoolByPoolName(String poolName);
}