package top.sharex.oes.entity;

public class Choice {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column choice.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column choice.isCorrect
     *
     * @mbggenerated
     */
    private Byte iscorrect;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column choice.question_id
     *
     * @mbggenerated
     */
    private Integer questionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column choice.content
     *
     * @mbggenerated
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table choice
     *
     * @mbggenerated
     */
    public Choice(Integer id, Byte iscorrect, Integer questionId, String content) {
        this.id = id;
        this.iscorrect = iscorrect;
        this.questionId = questionId;
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table choice
     *
     * @mbggenerated
     */
    public Choice() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column choice.id
     *
     * @return the value of choice.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column choice.id
     *
     * @param id the value for choice.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column choice.isCorrect
     *
     * @return the value of choice.isCorrect
     *
     * @mbggenerated
     */
    public Byte getIscorrect() {
        return iscorrect;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column choice.isCorrect
     *
     * @param iscorrect the value for choice.isCorrect
     *
     * @mbggenerated
     */
    public void setIscorrect(Byte iscorrect) {
        this.iscorrect = iscorrect;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column choice.question_id
     *
     * @return the value of choice.question_id
     *
     * @mbggenerated
     */
    public Integer getQuestionId() {
        return questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column choice.question_id
     *
     * @param questionId the value for choice.question_id
     *
     * @mbggenerated
     */
    public void setQuestionId(Integer questionId) {
        this.questionId = questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column choice.content
     *
     * @return the value of choice.content
     *
     * @mbggenerated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column choice.content
     *
     * @param content the value for choice.content
     *
     * @mbggenerated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}