package top.sharex.oes.entity;

import java.util.Date;

public class ExamQuestionsPool {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam_questions_pool.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam_questions_pool.pool_name
     *
     * @mbggenerated
     */
    private String poolName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam_questions_pool.description
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam_questions_pool.createTime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam_questions_pool.teacher_id
     *
     * @mbggenerated
     */
    private Integer teacherId;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_questions_pool
     *
     * @mbggenerated
     */
    public ExamQuestionsPool(Integer id, String poolName, String description, Date createtime, Integer teacherId) {
        this.id = id;
        this.poolName = poolName;
        this.description = description;
        this.createtime = createtime;
        this.teacherId = teacherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_questions_pool
     *
     * @mbggenerated
     */
    public ExamQuestionsPool() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam_questions_pool.id
     *
     * @return the value of exam_questions_pool.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam_questions_pool.id
     *
     * @param id the value for exam_questions_pool.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam_questions_pool.pool_name
     *
     * @return the value of exam_questions_pool.pool_name
     *
     * @mbggenerated
     */
    public String getPoolName() {
        return poolName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam_questions_pool.pool_name
     *
     * @param poolName the value for exam_questions_pool.pool_name
     *
     * @mbggenerated
     */
    public void setPoolName(String poolName) {
        this.poolName = poolName == null ? null : poolName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam_questions_pool.description
     *
     * @return the value of exam_questions_pool.description
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam_questions_pool.description
     *
     * @param description the value for exam_questions_pool.description
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam_questions_pool.createTime
     *
     * @return the value of exam_questions_pool.createTime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam_questions_pool.createTime
     *
     * @param createtime the value for exam_questions_pool.createTime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam_questions_pool.teacher_id
     *
     * @return the value of exam_questions_pool.teacher_id
     *
     * @mbggenerated
     */
    public Integer getTeacherId() {
        return teacherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam_questions_pool.teacher_id
     *
     * @param teacherId the value for exam_questions_pool.teacher_id
     *
     * @mbggenerated
     */
    public void setTeacherId(Integer teacherId) {
        this.teacherId = teacherId;
    }
}