package top.sharex.oes.entity;

import java.util.Date;

public class Exam {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam.title
     *
     * @mbggenerated
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam.question_num
     *
     * @mbggenerated
     */
    private Integer singleNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam.question_num
     *
     * @mbggenerated
     */
    private Integer multiNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam.question_num
     *
     * @mbggenerated
     */
    private Integer totalScore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam.start_time
     *
     * @mbggenerated
     */
    private Date startTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam.end_time
     *
     * @mbggenerated
     */
    private Date endTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam
     *
     * @mbggenerated
     */
    public Exam(Integer id, String title, Integer singleNum, Integer multiNum, Integer totalScore, Date startTime, Date endTime) {
        this.id = id;
        this.title = title;
        this.singleNum = singleNum;
        this.multiNum = multiNum;
        this.totalScore = totalScore;
        this.startTime = startTime;
        this.endTime = endTime;
    }

    public Exam(String title, Integer singleNum, Integer multiNum, Integer totalScore, Date startTime, Date endTime) {
        this.title = title;
        this.singleNum = singleNum;
        this.multiNum = multiNum;
        this.totalScore = totalScore;
        this.startTime = startTime;
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam
     *
     * @mbggenerated
     */
    public Exam() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam.id
     *
     * @return the value of exam.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam.id
     *
     * @param id the value for exam.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam.title
     *
     * @return the value of exam.title
     *
     * @mbggenerated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam.title
     *
     * @param title the value for exam.title
     *
     * @mbggenerated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam.question_num
     *
     * @return the value of exam.question_num
     *
     * @mbggenerated
     */
    public Integer getSingleNum() {
        return singleNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam.question_num
     *
     * @param singleNum the value for exam.question_num
     *
     * @mbggenerated
     */
    public void setSingleNum(Integer singleNum) {
        this.singleNum = singleNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam.question_num
     *
     * @return the value of exam.question_num
     *
     * @mbggenerated
     */
    public Integer getMultiNum() {
        return multiNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam.question_num
     *
     * @param  multiNum the value for exam.question_num
     *
     * @mbggenerated
     */
    public void setMultiNum(Integer multiNum) {
        this.multiNum = multiNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam.question_num
     *
     * @return the value of exam.question_num
     *
     * @mbggenerated
     */
    public Integer getTotalScore() {
        return totalScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam.question_num
     *
     * @param totalScore the value for exam.question_num
     *
     * @mbggenerated
     */
    public void setTotalScore(Integer totalScore) {
        this.totalScore = totalScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam.start_time
     *
     * @return the value of exam.start_time
     *
     * @mbggenerated
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam.start_time
     *
     * @param startTime the value for exam.start_time
     *
     * @mbggenerated
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam.end_time
     *
     * @return the value of exam.end_time
     *
     * @mbggenerated
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam.end_time
     *
     * @param endTime the value for exam.end_time
     *
     * @mbggenerated
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }
}